---
# tasks file for role-php
- name: Install remi-release
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
  become: yes
- name: Enable php
  ansible.builtin.shell: yum-config-manager --disable 'remi-php*'; yum-config-manager --enable remi-php{{ php_version_code }}
  become: yes
- name: Install php
  ansible.builtin.yum:
    name: php{{ php_version_code }}
  become: yes
- name: Install php extensions
  ansible.builtin.yum:
    name:
    - php{{ php_version_code }}-php-bcmath
    - php{{ php_version_code }}-php-ctype
    - php{{ php_version_code }}-php-curl
    - php{{ php_version_code }}-php-dom
    - php{{ php_version_code }}-php-fileinfo
    - php{{ php_version_code }}-php-gd
    - php{{ php_version_code }}-php-hash
    - php{{ php_version_code }}-php-iconv
    - php{{ php_version_code }}-php-intl
    - php{{ php_version_code }}-php-json
    - php{{ php_version_code }}-php-libxml
    - php{{ php_version_code }}-php-libxml
    - php{{ php_version_code }}-php-mbstring
    - php{{ php_version_code }}-php-openssl
    - php{{ php_version_code }}-php-openssl
    - php{{ php_version_code }}-php-pcre
    - php{{ php_version_code }}-php-pdo_mysql
    - php{{ php_version_code }}-php-simplexml
    - php{{ php_version_code }}-php-soap
    - php{{ php_version_code }}-php-sockets
    - php{{ php_version_code }}-php-sodium
    - php{{ php_version_code }}-php-spl
    - php{{ php_version_code }}-php-tokenizer
    - php{{ php_version_code }}-php-xmlwriter
    - php{{ php_version_code }}-php-xsl
    - php{{ php_version_code }}-php-zip
  become: yes
- name: Link php
  ansible.builtin.file:
    dest: /usr/bin/php
    src: /usr/bin/php{{ php_version_code }}
    state: link
  become: yes
