---
# tasks file for role-composer
- name: Install composer
  ansible.builtin.get_url:
    checksum: sha256:{{ composer_checksum }}
    dest: /usr/local/bin/composer
    mode: 0755
    url: https://getcomposer.org/download/{{ composer_version }}/composer.phar
  become: yes
