---
# tasks file for role-elasticsearch
- name: Install elasticsearch
  ansible.builtin.yum:
    checksum: sha512:https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-linux-x86_64.tar.gz.sha512
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm
  become: yes
